version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:$ELASTIC_STACK_VERSION
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: $JAVA_OPTS
      # Change discovery type to enable the production mode and bootstrap checks
      discovery.type: single-node
      bootstrap.memory_lock: $BOOTSTRAP_MEM_LOCK
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - internal

networks:
  internal:

volumes:
  elasticsearch: